# Generated by Django 5.1.7 on 2025-03-22 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Hotel Amenity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=2048)),
                ('hotel_description', models.TextField()),
                ('hotel_email', models.EmailField(default='abc@gmail.com', max_length=254)),
                ('hotel_phone', models.CharField(max_length=13, unique=True)),
                ('hotel_owner', models.CharField(max_length=255)),
                ('hotel_category', models.IntegerField(choices=[(1, 'ICY YELLOW'), (2, 'ICY WHITE'), (3, 'ICY BLACK')], default=1)),
                ('hotel_address', models.CharField(max_length=2048)),
                ('hotel_city', models.CharField(max_length=255)),
                ('hotel_state', models.CharField(max_length=255)),
                ('hotel_longitude', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Longitude')),
                ('hotel_latitude', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Latitude')),
                ('is_active', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('BLOCKED', 'Blocked')], default='UNVERIFIED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('hotel_amenities', models.ManyToManyField(to='hotel.hotelamenities')),
            ],
            options={
                'verbose_name': 'Hotels',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='media/hotel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_image', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.IntegerField(choices=[(1, 'Alpha'), (2, 'Beta'), (3, 'Gamma')], default=1)),
                ('room_description', models.TextField()),
                ('room_price', models.IntegerField(default=0)),
                ('room_count', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Room',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rooms_available', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
            options={
                'verbose_name': 'Room Availability',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['hotel_phone'], name='hotel_hotel_hotel_p_f0e366_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['id'], name='hotel_hotel_id_487682_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel_id', 'room_type'], name='hotel_room_hotel_i_99febe_idx'),
        ),
        migrations.AddIndex(
            model_name='roomavailability',
            index=models.Index(fields=['date'], name='hotel_rooma_date_409663_idx'),
        ),
    ]
