# Generated by Django 5.1.7 on 2025-03-20 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Hotel Amenity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=2048)),
                ('hotel_description', models.TextField()),
                ('hotel_email', models.EmailField(default='abc@gmail.com', max_length=254, unique=True)),
                ('hotel_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('hotel_owner', models.CharField(max_length=255)),
                ('hotel_category', models.IntegerField(choices=[(1, 'ICY YELLOW'), (2, 'ICY WHITE'), (3, 'ICY BLACK')], default=1)),
                ('hotel_address', models.CharField(max_length=2048)),
                ('hotel_city', models.CharField(max_length=255)),
                ('hotel_state', models.CharField(max_length=255)),
                ('hotel_longitude', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Longitude')),
                ('hotel_latitude', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Latitude')),
                ('is_active', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('BLOCKED', 'Blocked')], default='UNVERIFIED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('hotel_amenities', models.ManyToManyField(to='hotel.hotelamenities')),
            ],
            options={
                'verbose_name': 'Hotels',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='media/hotel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_image', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Images',
                'managed': True,
            },
        ),
    ]
