# Generated by Django 5.1.7 on 2025-03-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_email',
            field=models.EmailField(default='abc@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_latitude',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_longitude',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Longitude'),
        ),
    ]
