# Generated by Django 5.1.7 on 2025-03-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('user_location', models.CharField(max_length=255)),
                ('user_profileImage', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
                'indexes': [models.Index(fields=['user_phone'], name='user_user_ph_cc8b62_idx'), models.Index(fields=['id'], name='user_id_f1790c_idx')],
            },
        ),
    ]
