# Generated by Django 5.1.7 on 2025-03-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_user_profileimage_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(help_text='Enter your phone number', max_length=20, unique=True, verbose_name='Phone Number'),
        ),
    ]
